DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(200) NOT NULL,
	registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post (
	id SERIAL PRIMARY KEY,
	title VARCHAR(150) NOT NULL,
	short_description VARCHAR(200),
	content TEXT NOT NULL,
	image VARCHAR(100),
	date_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_id INTEGER REFERENCES users(id)
);